# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish console app

# Declaring custom variables
env:
  PROJECT_NAME: Flamencode
  WINDOWS_RUNTIME: winx64
  WINDOWS_FOLDER: Windows-x64
  MACOS_RUNTIME_X64: osx-x64
  MACOS_FOLDER_X64: MacOS-x64
  MACOS_RUNTIME_ARM: osx-arm
  MACOS_FOLDER_ARM: MacOS-arm
  LINUX_RUNTIME: linux-x64
  LINUX_FOLDER_ARM: a
  RELEASE_FOLDER: release
  OPERATIVE_SYSTEM_RUNTIMES: win-x64 osx-x64 linux-x64
  OPERATIVE_SYSTEM_FOLDERS: Windows64 Macos64 Linux64
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ABC: '["hola", "mundo"]'
  ABCD: '("hola" "mundo")'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v3 
    
    - name: Prueba
      run: |
        e=${{ fromJSON(env.ABC) }}
        echo $e
        for (( i=0; i<${#e[@]}; i+=2 )); do
          a=${e[i]}
          b=${e[i+1]}
          echo "a=$a, b=$b"
        done
        cd release
        ls
        
    # Build project to the release-folder
    - name: Build .NET Project
      run: |
        runtime=${{matrix.runtime}}
        folder=${{matrix.folder}}
        dotnet publish $PROJECT_NAME/$PROJECT_NAME.csproj -r $runtime -c Release -o release/$folder --nologo --self-contained true /p:PublishSingleFile=true /p:DebugType=None /p:DebugSymbols=false
        cd release
        ls


          
     # Create release
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }} # Reemplaza con la versión que quieras asignar a tu release
        release_name: Release ${{ github.event.inputs.version }} # Nombre de la release
        body: '' # Cuerpo de la release
        draft: false
        prerelease: false
        
    # Upload release
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/*/* # Folders with executables
        asset_name: Flamencode-{{filename}}.exe # Nombre del ejecutable en la Release
        asset_content_type: application/octet-stream
    
    - name: List Assets
      run: |
        echo "Los siguientes activos se han agregado a la versión de lanzamiento:"
        echo "${{ steps.upload_assets.outputs.asset_names }}"
